blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions 
    url: https://github.com/Josh-McFarlin/js-image-lib/discussions
    about: Please ask and answer questions here.
